prompts:
  [
    'prompt_chat.js',
    'prompt_string.js',
    'prompt_multiple.js:prompt2',
    'prompt_python.py',
  ]
providers: [openai:gpt-3.5-turbo-0613]
tests:
  - vars:
      topic: 天気
  - vars:
      topic: 桜
  - vars:
      topic: ローマ帝国
