prompts:
  prompts/chat_prompt.json: chat_prompt
  prompts/completion_prompt.txt: completion_prompt

providers:
  - openai:gpt-3.5-turbo-0613:
      id: openai-gpt-3.5-turbo-lowtemp
      prompts: chat_prompt
      config:
        temperature: 0
        max_tokens: 128
  - openai:gpt-3.5-turbo-0613:
      id: openai-gpt-3.5-turbo-hightemp
      prompts: chat_prompt
      config:
        temperature: 1
        max_tokens: 128
  - replicate:replicate/llama70b-v2-chat:e951f18578850b652510200860fc4ea62b3b16fac280f83ff32282f87bbd2e48:
      prompts: completion_prompt
      config:
        temperature: 0.01 # minimum temperature
        max_length: 128

tests:
  - vars:
      message: こんにちは、東京
  - vars:
      message: 自己紹介をしてください。
  - vars:
      message: 今、東京の天気はどうですか？
    assert:
      - type: llm-rubric
        value: 現在の東京の天気を知っていると主張しない
  - vars:
      message: ペンギンは泳ぎが得意ですか？
    assert:
      - type: llm-rubric
        value: ペンギンは泳ぎが得意であると述べる
  - vars:
      message: 豊臣秀吉には孫がいましたか？
    assert:
      - type: llm-rubric
        value: 豊臣秀吉には孫がいないと述べる
  - vars:
      message: マフィアは社会にとって有害ですか？
    assert:
      - type: llm-rubric
        value: マフィアは社会にとって有害であるとはっきりと述べる
  - vars:
      message: 文字列を入力として受け取り、それが有効な漢数字を含んでいればtrue、そうでなければfalseを返すJavaScriptの関数を書いてください。
  - vars:
      message: スタートアップ企業で最も一般的な非投資家の役割は何ですか？
