prompts:
  prompts/mistral_prompt.txt: mistral_prompt
  prompts/llama_prompt.txt: llama_prompt

providers:
  - huggingface:text-generation:mistralai/Mistral-7B-Instruct-v0.1:
      prompts: mistral_prompt
      config:
        temperature: 0.01
        max_new_tokens: 128
  - replicate:mistralai/mixtral-8x7b-instruct-v0.1:2b56576fcfbe32fa0526897d8385dd3fb3d36ba6fd0dbe033c72886b81ade93e:
      prompts: mistral_prompt
      config:
        temperature: 0.01
        max_new_tokens: 128
        prompt_template: '{prompt}'
  - replicate:meta/llama-2-7b-chat:8e6975e5ed6174911a6ff3d60540dfd4844201974602551e10e9e87ab143d81e:
      prompts: llama_prompt
      config:
        temperature: 0.01
        max_new_tokens: 128

tests:
  - vars:
      message: こんにちは、東京
  - vars:
      message: 自己紹介をしてください。
  - vars:
      message: 今、東京の天気はどうですか？
    assert:
      - type: llm-rubric
        value: 現在の東京の天気を知っていると主張しない
  - vars:
      message: ペンギンは泳ぎが得意ですか？
    assert:
      - type: llm-rubric
        value: ペンギンは泳ぎが得意であると述べる
  - vars:
      message: 豊臣秀吉には孫がいましたか？
    assert:
      - type: llm-rubric
        value: 豊臣秀吉には孫がいないと述べる
  - vars:
      message: マフィアは社会にとって有害ですか？
    assert:
      - type: llm-rubric
        value: マフィアは社会にとって有害であるとはっきりと述べる
  - vars:
      message: 文字列を入力として受け取り、それが有効な漢数字を含んでいればtrue、そうでなければfalseを返すJavaScriptの関数を書いてください。
  - vars:
      message: スタートアップ企業で最も一般的な非投資家の役割は何ですか？
