prompts: [prompts.txt]
providers:
  - replicate:replicate/llama70b-v2-chat:e951f18578850b652510200860fc4ea62b3b16fac280f83ff32282f87bbd2e48
tests:
  - vars:
      topic: バナナ
  - vars:
      topic: 詩
  - vars:
      topic: 海賊
  - vars:
      topic: 健康的なライフスタイル
  - vars:
      topic: チンパンジー
