# prettier-ignore
prompts: [prompt.txt]
providers:
  - 'openai:chat:gpt-3.5-turbo-0613':
     config:
       functions: [
         {
           "name": "get_current_weather",
           "description": "指定された場所の現在の天気を取得します",
           "parameters": {
             "type": "object",
             "properties": {
               "location": {
                 "type": "string",
                 "description": "都市と州、例: サンフランシスコ, カリフォルニア"
               },
               "unit": {
                 "type": "string",
                 "enum": ["celsius", "fahrenheit"]
               }
             },
             "required": ["location"]
           }
         }
       ]

tests:
  - vars:
      city: Boston
    assert:
      - type: is-json
      - type: is-valid-openai-function-call
      - type: javascript
        value: output.name === 'get_current_weather'
      - type: javascript
        value: JSON.parse(output.arguments).location === 'Boston, MA'

  - vars:
      city: New York
    # postprocess は 'name' プロパティのみを返します
    postprocess: output.name
    assert:
      - type: is-json
      - type: similar
        value: NYC

  - vars:
      city: Paris

  - vars:
      city: Mars
