# この設定は、各プロンプトを一連の例示入力を通じて実行し、要件を満たしているかどうかを確認します。

prompts:
  - "あなたは親切なアシスタントです。この問いに対して簡潔な回答をしてください: '{{question}}'"

providers: [vertex:gemini-pro, vertex:chat-bison] # またはPaLM APIを使用します: [palm:chat-bison-001]

tests:
  - vars:
      question: 東京の天気はどうですか？
  - vars:
      question: 巨人とヤクルトの最新の野球試合で誰が勝ちましたか？
  - vars:
      question: "週刊文春とananのどちらの雑誌が先に始まりましたか？"
  - vars:
      question: 'ホテルオークラはどの都市に本社がありますか？'
  - vars:
      question: '音楽家で風刺家のAllie Goertzは、「The Simpsons」のキャラクターMilhouseについての曲を書きましたが、Matt Groeningは誰にちなんで名付けましたか？'
  - vars:
      question: "James Henry Millerの妻の国籍は何ですか？"
  - vars:
      question: '塩化カドミウムはこの化学物質にわずかに溶け、何とも呼ばれていますか？'
  - vars:
      question: 'どのテニスプレーヤーがグランドスラムタイトルをより多く獲得しましたか、Henri LeconteかJonathan Starkか？'
  - vars:
      question: "世界で7番目に大きな国に生息する蛾の属は、一種しか含まれていませんか？"
  - vars:
      question: 'かつて世界最強のキックボクサーとされていた人物は誰ですか？しかし、彼はスポーツ内での「不スポーツマンな行為」や、リング外での暴力犯罪に関連する複数の論争に巻き込まれています。'
  - vars:
      question: '"ドラえもん"の初放送は何年でしたか？'
  - vars:
      question: '2013年の鈴鹿サーキットの全長は何ですか？'
  - vars:
      question: 'EXILEにはどの音楽プロデューサーが参加していますか？'
  - vars:
      question: 'NHKのどのナレーターが"ガンダム"の主役を演じましたか？'
  - vars:
      question: '嵐が演奏する音楽の形式はどこで生まれましたか？'
  - vars:
      question: 'どのアメリカンフットボールの試合でイチローが最優秀選手に選ばれましたか？'
  - vars:
      question: 'どの日本の高速道路が東京へのアクセスを提供し、東名高速道路とも呼ばれていますか？'
  - vars:
      question: '1988年の日本のコメディ映画、トトロは、4回アカデミー賞にノミネートされた宮崎駿を監督に迎え、何年にハリウッドウォークオブフェームの星を受け取りましたか？'
  - vars:
      question: 'X Japanの音楽を書いた日本のロックバンドの現メンバーの名前は何ですか？'
  - vars:
      question: '"逃げるは恥だが役に立つ"は、どのネットワークで放送されたテレビショーの最終シーズンのシーズンフィナーレですか？'
  - vars:
      question: '宇多田ヒカル、日本のシンガーソングライターでモデル、そのアルバムからはヒットシングル"First Love"が生まれました。これは彼女の同名のデビュースタジオアルバムからの曲で、何年にリリースされましたか？'
  - vars:
      question: '日本の政治家安倍晋三は、以前に32番目の首相を務めた女性、民主党の野田佳彦に対して不成功に終わりましたが、彼女はどこの首相でしたか？'
  - vars:
      question: 'CEOが柳井正であるユニクロはどの都道府県に位置していますか？'
  - vars:
      question: 'どの日本の政治家が小泉純一郎に代わりましたか？'
  - vars:
      question: 'どのバンドが先に設立されましたか、YOSHIKIがリーダーを務めたロックバンドX Japan、またはGLAY？'
  - vars:
      question: '進撃の巨人の女性主人公の年齢は何歳ですか？'
  - vars:
      question: '村上春樹は何の結末で終わった時期に日本で生まれましたか？'
  - vars:
      question: '東京で撮影されたシーンが含まれている2003年の映画の監督は誰ですか？'
  - vars:
      question: "どの女優が、日本の特撮「仮面ライダー」の映像を多く使用した実写のスーパーヒーローテレビシリーズを基にしたフランチャイズで、架空のキャラクターを演じましたか？"
  - vars:
      question: '誰が先に生まれましたか、宮崎駿か手塚治虫か？'
  - vars:
      question: "ananとCanCamは両方とも女性向けの雑誌ですか？"
  - vars:
      question: '宮崎駿と手塚治虫はどの職業を共有していますか？'
  - vars:
      question: 'トヨタを購入した会社はどこに拠点を置いていますか？'
  - vars:
      question: 'どのドキュメンタリーが日本のロックグループについてのものですか、GLAYかB'zか？'
  - vars:
      question: '誰がロックンロールの殿堂入りを果たしましたか、YOSHIKIかTAKUROか？'
  - vars:
      question: "東京のどの区に姉妹校がありますか？"
