prompts: [prompts.txt]
providers: [bedrock:anthropic.claude-v2]
tests:
  - vars:
      question: 東京の天気は何ですか？
  - vars:
      question: 最新の巨人とカープの野球試合は誰が勝ちましたか？
  - vars:
      question: '週刊少年ジャンプと週刊少年マガジン、どちらが先に創刊されましたか？'
  - vars:
      question: '東京タワーの高さは何メートルですか？'
  - vars:
      question: '宮崎駿が監督を務めた映画『となりのトトロ』は何年に公開されましたか？'
  - vars:
      question: "村上春樹の小説「ノルウェイの森」の主人公の名前は何ですか？"
  - vars:
      question: '富士山の標高は何メートルですか？'
  - vars:
      question: '大相撲の最高位は何と呼ばれますか？'
  - vars:
      question: "日本の国鳥は何ですか？"
  - vars:
      question: '日本の国花は何ですか？'
  - vars:
      question: '日本の首都はどこですか？'
  - vars:
      question: '日本の最高峰は何ですか？'
  - vars:
      question: '日本の国民の日は何月何日ですか？'
  - vars:
      question: '日本の国歌の名前は何ですか？'
  - vars:
      question: '日本の最大の湖は何ですか？'
  - vars:
      question: '日本の最長の川は何ですか？'
  - vars:
      question: '日本の最大の都市は何ですか？'
  - vars:
      question: '日本の最南端の島は何ですか？'
  - vars:
      question: '日本の最北端の島は何ですか？'
  - vars:
      question: '日本の国土の面積は何平方キロメートルですか？'
  - vars:
      question: '日本の人口は約何人ですか？'
  - vars:
      question: '日本の国旗の色は何色ですか？'
  - vars:
      question: '日本の通貨単位は何ですか？'
  - vars:
      question: '日本の国語は何ですか？'
  - vars:
      question: '日本の国民の平均寿命は何歳ですか？'
  - vars:
      question: '日本の最大の島は何ですか？'
  - vars:
      question: '日本の最大の企業は何ですか？'
  - vars:
      question: '日本の最大の空港は何ですか？'
  - vars:
      question: '日本の最大の宗教は何ですか？'
  - vars:
      question: '日本の最大の新聞は何ですか？'
  - vars:
      question: '日本の最大のテレビ局は何ですか？'
  - vars:
      question: '日本の最大のスポーツは何ですか？'
  - vars:
      question: '日本の最大の祭りは何ですか？'
  - vars:
      question: '日本の最大の美術館は何ですか？'
  - vars:
      question: '日本の最大の図書館は何ですか？'
  - vars:
      question: '日本の最大の公園は何ですか？'
